services:
  db:
    image: postgres:16
    container_name: utstyr_db
    environment:
      POSTGRES_USER: utstyr
      POSTGRES_PASSWORD: utstyr
      POSTGRES_DB: utstyr
    ports:
      - "5432:5432"
    volumes:
      - utstyr_db_data:/var/lib/postgresql/data
  https:
    image: caddy:2
    container_name: utstyr_https
    depends_on:
      - db
    environment:
      - LAN_HOST=${LAN_HOST:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
volumes:
  utstyr_db_data:
  caddy_data:
  caddy_config:
